server:
  port: 8082
  servlet:
    context-path: /api


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Wjdals12!
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50  # 50개씩 묶어서 배치 실행
          order_inserts: true
          order_updates: true  # 같은 테이블 업데이트를 묶음

  messages:
    basename: messages

## 업로드 파일 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
      file-size-threshold: 2KB

external:
  user-service:
    protocol: http
    host: localhost
    port: 8081
    api-key: test

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

file:
  upload:
    path: uploads\\ # 파일 업로드 기본 경로

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa


scheduler:
  hot-score:
    enable: true
    time-weight-update:
      cron: "0 0 * * * *"  # 매 시간 정각
      enabled: true
    full-recalculate:
      cron: "0 0 3 * * *"  # 매일 새벽 3시
      enabled: true