server:
  port: 8082
  servlet:
    context-path: /api


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/playground?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Wjdals12!
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: messages

## 업로드 파일 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
      file-size-threshold: 2KB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

file:
  upload:
    path: uploads\\ # 파일 업로드 기본 경로

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa